### ISSUE TITLE
serial_packet.c is missing from the repo

### ISSUE THREAD

**Issue by robertrau** [Lauszus/blhost#2]
Kristian,

I am trying to build on Mac OS X version 10.13.6. The file serial_packet.c is not found. I am stuck on 10.13.6 due to other software restrictions. I am a hardware engineer trying to FLASH a little project I designed. Can you help?

Thank you for your time,

Bob Rau

**Comment by robertrau** [comment]
Kristian,

I am also finding a number of other missing files:
fsl_common.h
fsl_types.h
fsl_status.h
property.c

and others.

Thank you for any help,

Bob Rau

**Comment by Lauszus** [comment]
There is no such file called `serial_packet.h`, `fsl_types.h`, `fsl_status.h` and `property.c` in this project. I'm not sure why you think you need those specific files?

`fsl_common.h` can be found here:  https://github.com/Lauszus/blhost/tree/master/src/drivers/common

Anyway just use make to compile the project:

```bash
make -j2 -C validation/blhost/gcc
```

You also need to install hidapi on your Mac using [Homebrew](https://brew.sh/index_da):

```bash
brew install hidapi
```

**Comment by robertrau** [comment]
Kristian,

Sorry, I saw the x-code project and launch that.

Thank you for your help.

Bob

**Comment by Lauszus** [comment]
Good to hear that you got it working.
