### ISSUE TITLE
Buspal mode not works

### ISSUE THREAD

**Issue by FabioGenesy** [Lauszus/blhost#3]
Hi Lauszus,
I am using your version of blhost compiled for Raspberry.
In normal mode it works quite well, while I can't get it to work in buspal mode.
I would to know, have you ever tried to use this mode?
Why did you need to change source code? Didn't it work correctly for Raspberry?

Thank you in advance!

**Comment by Lauszus** [comment]
No I have never tried it with buspal.

No it did not work out of the box, as there was several issue with the code. Fx: https://github.com/Lauszus/blhost/commit/12c39dff5c3d210d495ad341b3c02aec4a5ef2ee

For a full list of changes take a look at the commit history: https://github.com/Lauszus/blhost/commits/master
