### ISSUE TITLE
building/running for ABI arm64-v8a (aarch64 instruction set)

### ISSUE THREAD

**Issue by mejha** [Lauszus/blhost#4]
Hello,

Is there any way to build this for ABI arm64-v8a? I was not able to find library for udev for aarch64.
I would like to use blhost in Android device, it can run armv7l release but it's missing udev library.

Is there maybe some workaround for this? Is perhaps some other tool available for this that can run on Android?

**Comment by Lauszus** [comment]
I would make a new Dockerfile based on the `armv7l` one: https://github.com/Lauszus/blhost/blob/master/Dockerfile.armv7l, but use the following image instead: https://hub.docker.com/r/balenalib/aarch64-debian

**Comment by Lauszus** [comment]
FYI I've also made a Python version: https://github.com/Lauszus/pyblhost, which you might find useful.

**Comment by mejha** [comment]
@Lauszus thank you for your suggestion.

I tried creating new Dockerfille (balenalib/aarch64-debian:latest) as you have mentioned, added line `RUN apt-get install -y libstdc++6` and it builds just fine. Thanks.
